version: "3"

services:
  simulation:
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - "$HOME/.Xauthority:/root/.Xauthority:rw"
    network_mode: host
    command: ["runBarabasiGraphic"]
